### ISSUE TITLE
Form Fields not working (save,Delete,Move up,MoveDown) - Quote Line Editor

### ISSUE THREAD

**Issue by gvkn009** [scottdurow/SparkleXrm#78] opened 2015-11-19 05:09 UTC
[Client.txt](https://github.com/scottdurow/SparkleXrm/files/38620/Client.txt)
[QuotelineEditor.txt](https://github.com/scottdurow/SparkleXrm/files/38621/QuotelineEditor.txt)

I am able to retrieve the data but not able to save,add or delete.

Your help will be appreciated.

Thanks,

Venkata

**Comment by scottdurow** [comment] 2015-11-20 17:09
Duplicate of #77

**Closed by scottdurow** 2015-11-20 17:09 UTC
Labels: duplicate
