### ISSUE TITLE
An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.

### ISSUE THREAD

**Issue by MamadouABah** [scottdurow/SparkleXrm#320] opened 2019-04-14 00:09 UTC
Unable to connect using to deploy plugin, tried leaving server name empty as well but still no luck.  I sync the time with server using command prompt but still getting the error.  I'm on latest for all nuget packages as well and spkl.

spkl Task Runner v1.0.226.1     Tasks v1.0.226.1
Enter a CRM server name and port [crm.dynamics.com]: crm4.dynamics.com
Is this organization provisioned in Microsoft Office 365 (y/n) [y]: y

 Enter Username [xxxx@microsoft.com]: xxxx@microsoft.com
 Enter Password: ***************

The application terminated with an error.
An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.

Server stack trace:
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.ProcessReply(Message reply, SecurityProtocolCorrelationState correlationState, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.ServiceModel.Security.IWSTrustContract.Issue(Message message)
   at System.ServiceModel.Security.WSTrustChannel.Issue(RequestSecurityToken rst, RequestSecurityTokenResponse& rstr)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Issue(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateFederatedTokenWithOrgIdForCRM(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateOnlineFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceConfiguration.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetProxy[TService,TProxy](Configuration currentConfig)
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetDiscoveryProxy()
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetOrganizationAddress()
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetServerConfiguration(Boolean ignoreLocalPrincipal)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)

**Comment by MamadouABah** [comment] 2019-04-15 17:55
I'm wondering if this is not because our org uses multi factor authentication.
I tried creating application user with a client id and secret to authenticate using that method but I get this error:
The application terminated with an error.
clientCredentials.UserName.UserName or clientCredentials.Windows.ClientCredential.UserName MUST be populated!
   at Microsoft.Xrm.Sdk.ClientExceptionHelper.Assert(Boolean condition, String message)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.GetIdentityProvider(ClientCredentials clientCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateOnlineFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceConfiguration.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetProxy[TService,TProxy](Configuration currentConfig)
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetDiscoveryProxy()
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetOrganizationAddress()
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetServerConfiguration(Boolean ignoreLocalPrincipal)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)

**Comment by MamadouABah** [comment] 2019-04-15 17:56
Any help would greatly appreciated

**Comment by stephenjtyrrell** [comment] 2019-05-16 13:17
The issue is your MFA, spkl doesn't work with O365 MFA. You can test this by spinning up a trial environment and walking through the connection steps.

**Comment by scottdurow** [comment] 2019-12-12 17:07
Duplicate of #308

**Closed by scottdurow** 2019-12-12 17:07 UTC
