### ISSUE TITLE
Plugins: Run in User's Context-option missing

### ISSUE THREAD

**Issue by vandyckth** [scottdurow/SparkleXrm#415] opened 2021-03-28 13:19 UTC
When using the CrmPluginRegistrationAttribute-class, there doesn't seem to be any way to pass the a name or ID of a systemuser to adjust the option 'Run in User's Context' that is provided by the PluginRegistration tool. Could you add this please?

Thanks in advance.

**Comment by scottdurow** [comment] 2021-04-14 15:38
Duplicate of #180

**Closed by scottdurow** 2021-04-14 15:38 UTC
